### ISSUE TITLE
As a user I want a better error message when I use an invalid city

### ISSUE THREAD

**Issue by eebbesen** [eebbesen/caruby2go#5]
If you provide a city that's not recognized by Car2Go you'll get a 400 as a response (see below).  This error doesn't indicate the likely cause of the problem.

Intercept 400s and direct users to the unofficial list of city names.

```
$ CONSUMER_KEY=getaround bin/caruby2go v nowheresville
/Users/user/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:358:in `open_http': 400 Bad Request (OpenURI::HTTPError)
```

**Comment by eebbesen** [comment]
Added to message:

```
git pullCONSUMER_KEY=getaround bin/caruby2go v blah --raw
/Users/eebbesen/proj3/caruby2go/lib/caruby2go.rb:44:in `rescue in issue_get': Car2Go probably doesn't like the city you entered: blah (RuntimeError)
    from /Users/eebbesen/proj3/caruby2go/lib/caruby2go.rb:40:in `issue_get'
    from /Users/eebbesen/proj3/caruby2go/lib/caruby2go.rb:29:in `vehicles'
    from bin/caruby2go:47:in `call_api'
    from bin/caruby2go:15:in `vehicles'
    from /Users/eebbesen/.rvm/gems/ruby-2.2.0@caruby2go/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/eebbesen/.rvm/gems/ruby-2.2.0@caruby2go/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/eebbesen/.rvm/gems/ruby-2.2.0@caruby2go/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/eebbesen/.rvm/gems/ruby-2.2.0@caruby2go/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from bin/caruby2go:66:in `<main>'
```
